# Generated by Django 3.2.8 on 2021-11-03 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referencies', '0002_auto_20211103_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'max_length': 'Title must be a upto %(length)s symbols text', 'required': 'Title is requred'}, help_text='Unique if possible instrument name', max_length=255, verbose_name='Title')),
                ('default_validation_interval', models.PositiveSmallIntegerField(choices=[(6, '6\xa0mo.'), (12, '12\xa0mo.'), (24, '24\xa0mo.'), (36, '36\xa0mo.'), (48, '48\xa0mo.'), (60, '60\xa0mo.'), (72, '72\xa0mo.'), (96, '96\xa0mo.')], error_messages={'required': 'Validation interval is requred'})),
                ('precision_class', models.CharField(error_messages={'max_length': 'Precision class must be a upto %(length)s symbols text', 'required': 'Prec. class is requred'}, help_text='Instrument precision class', max_length=255, verbose_name='Title')),
                ('precision_lower_bound', models.DecimalField(decimal_places=5, max_digits=10)),
                ('precision_upper_bound', models.DecimalField(decimal_places=5, max_digits=10)),
                ('sweep_mark', models.BooleanField(default=False, help_text='Set if item no more be applyable', verbose_name='Hidden')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'max_length': 'Title must be a upto %(length)s symbols text', 'required': 'Title is requred'}, help_text='Unique if possible instrument name', max_length=255, verbose_name='Title')),
                ('accouning_id', models.CharField(error_messages={'max_length': 'Acc. ID must be a upto %(length)s symbols text', 'required': 'Acc. ID is requred'}, help_text='Unique acc. ID', max_length=10, unique=True, verbose_name='Acc. ID')),
                ('part_of_reports', models.PositiveSmallIntegerField(choices=[(1, 'Part one'), (2, 'Part two'), (3, 'Part three')], error_messages={'required': 'Part of report is requred'})),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Instr. cat. one'), (2, 'Instr. cat. two'), (3, 'Instr. cat. three')], error_messages={'required': 'Cathegory is requred'})),
                ('sweep_mark', models.BooleanField(default=False, help_text='Set if item no more be applyable', verbose_name='Hidden')),
                ('displacement', models.ForeignKey(error_messages={'required': 'Displacement is requred'}, help_text='Displacement', limit_choices_to={'sweep_mark': False}, on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='referencies.place', verbose_name='Instrument displacement')),
                ('instrument_type', models.ForeignKey(error_messages={'required': 'type is requred'}, help_text='Instrument type', limit_choices_to={'sweep_mark': False}, on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='instruments.instrumenttype', verbose_name='Instrument type')),
            ],
        ),
    ]
