# Generated by Django 3.2.8 on 2021-11-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumenttype',
            name='precision_class',
            field=models.CharField(error_messages={'max_length': 'Precision class must be a upto %(length)s symbols text', 'required': 'Prec. class is requred'}, help_text='Instrument precision class', max_length=255, verbose_name='Precision class'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='precision_lower_bound',
            field=models.DecimalField(decimal_places=5, help_text='decimal [10,5]', max_digits=10, verbose_name='Precision lower bound'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='precision_upper_bound',
            field=models.DecimalField(decimal_places=5, help_text='decimal [10,5]', max_digits=10, verbose_name='Precision upper bound'),
        ),
    ]
