# Generated by Django 3.2.8 on 2021-10-31 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contragent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'max_length': 'Title must be a upto %(length)s symbols text', 'required': 'Title is requred'}, help_text='Unique if possible contragent name', max_length=255, verbose_name='Title')),
                ('unp', models.CharField(db_index=True, error_messages={'max_length': 'UNP must be exact %(length)s symbols length', 'min_length': 'UNP must be exact %(length)s symbols length', 'required': 'Title is requred'}, help_text='Unique tax payer number (belorussian)', max_length=9, unique=True, verbose_name='UNP')),
                ('ownership_form', models.CharField(choices=[('JSC', 'JSC'), ('LTD', 'LTD'), ('RUE', 'RUE'), ('RDTUE', 'RDTUE'), ('GU', 'GU')], error_messages={'required': 'Ownership form is requred'}, max_length=15)),
                ('contacts', models.TextField(blank=True, help_text='Contacts information', verbose_name='Hidden')),
                ('sweep_mark', models.BooleanField(default=True, help_text='Set if item no more be applyable', verbose_name='Hidden')),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(error_messages={'required': 'License is requred'}, help_text='Actual license number', max_length=50, verbose_name='License number')),
                ('license_expiry_date', models.DateField(error_messages={'required': 'License expiry date is requred'}, help_text='License expiry date', verbose_name='License expiry date')),
                ('sweep_mark', models.BooleanField(default=True, help_text='Set if item no more be applyable', verbose_name='Hidden')),
                ('contragent', models.ForeignKey(error_messages={'required': 'Contragent is requred'}, help_text='Related contragent', on_delete=django.db.models.deletion.CASCADE, related_name='valdator', to='referencies.contragent', verbose_name='Contragent')),
            ],
        ),
    ]
