# Generated by Django 3.2.8 on 2021-11-03 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contragent',
            name='sweep_mark',
            field=models.BooleanField(default=False, help_text='Set if item no more be applyable', verbose_name='Hidden'),
        ),
        migrations.AlterField(
            model_name='validator',
            name='contragent',
            field=models.ForeignKey(error_messages={'required': 'Contragent is requred'}, help_text='Related contragent', limit_choices_to={'sweep_mark': False}, on_delete=django.db.models.deletion.CASCADE, related_name='valdators', to='referencies.contragent', verbose_name='Contragent'),
        ),
        migrations.AlterField(
            model_name='validator',
            name='sweep_mark',
            field=models.BooleanField(default=False, help_text='Set if item no more be applyable', verbose_name='Hidden'),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'max_length': 'Title must be a upto %(length)s symbols text', 'required': 'Title is requred'}, help_text='Unique if possible place name', max_length=255, verbose_name='Title')),
                ('sweep_mark', models.BooleanField(default=False, help_text='Set if item no more be applyable', verbose_name='Hidden')),
                ('contragent', models.ForeignKey(error_messages={'required': 'Contragent is requred'}, help_text='Related contragent', limit_choices_to={'sweep_mark': False}, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='referencies.contragent', verbose_name='Contragent')),
            ],
        ),
    ]
